### ISSUE TITLE
Go to Flathub

### ISSUE THREAD

**Issue by fisuri** [appelgriebsch/com.jetbrains.RustRover#1]
I suggest you upload your application to [Flathub](https://docs.flathub.org/docs/for-app-authors/submission/), it will be more convenient this way.

**Comment by appelgriebsch** [comment]
there is already a ticket for this: https://github.com/flathub/flathub/pull/4597. Looks like they reached out to Jetbrains for approval / support for official flatpak packages.

**Comment by fisuri** [comment]
Thanks for the answer, I didn't know I already had a ticket.
